# Generated by Django 4.0.3 on 2022-03-29 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('campaign_goal', models.CharField(choices=[('REVENUE', 'Revenue'), ('BRAND', 'Brand'), ('TRAFFIC', 'Traffic')], default='REVENUE', max_length=8)),
                ('campaign_goal_values', models.DecimalField(decimal_places=0, max_digits=12)),
                ('description', models.CharField(max_length=250)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
